<?php
$pid = getmypid();

error_log($pid . ' ***** FILTER MESSAGE START ***** ' . $_SERVER['REQUEST_URI']);

error_log($pid . ' ' . $_SERVER['HTTP_USER_AGENT']);

error_log($pid . ' last_update_ ' . md5_file('/app/www/last_update.txt'));
error_log($pid . ' X-Access-Key ' . $_SERVER['HTTP_X_ACCESS_KEY']);
$key = $_SERVER['HTTP_X_ACCESS_KEY'];

error_log($pid . ' X-Forwarded-For ' . $_SERVER['HTTP_X_FORWARDED_FOR']);
$forward_count = count(explode(' ', $_SERVER['HTTP_X_FORWARDED_FOR']));

error_log($pid . ' Forwarded Count ' . $forward_count);

$url = 'https://logs-01.loggly.com/inputs/' . getenv('LOGGLY_TOKEN') . '/tag/' . $_SERVER['SERVER_NAME'] . '/';

if (preg_match('/(Trident|Edge)/', $_SERVER['HTTP_USER_AGENT']) || $forward_count != 3 || $key != md5_file('/app/www/last_update.txt'))
{
  error_log($pid . ' #*#*#*#*# IE or Edge or Direct Connect Or X-Access-Key Unmatch #*#*#*#*#');
  header('HTTP', true, 403);
  
  $message =
    'D 403 ' .
    $_SERVER['SERVER_NAME'] . ' ' .
    $_SERVER['HTTP_X_FORWARDED_FOR'] . ' ' .
    $_SERVER['REMOTE_USER'] . ' ' .
    $_SERVER['REQUEST_METHOD'] . ' ' .
    $_SERVER['REQUEST_URI'] . ' ' .
    $_SERVER['HTTP_USER_AGENT'];

  $context = array(
    "http" => array(
      "method" => "POST",
      "header" => array(
        "Content-Type: text/plain"
        ),
      "content" => $message
      )
    );

  $res = file_get_contents($url, false, stream_context_create($context));

  error_log($pid . ' ' . $res);
    
  error_log($pid . ' ***** FILTER MESSAGE FINISH ***** ' . $_SERVER['REQUEST_URI']);
  return;
}

error_log($pid . ' ***** STDIN START ***** ' . $_SERVER['REQUEST_URI']);
$buf = file_get_contents('php://stdin');
error_log($pid . ' ***** STDIN FINISH ***** ' . $_SERVER['REQUEST_URI']);

$arr_buf = preg_split('/^\r\n/m', $buf, 2);
$header = $arr_buf[0];
$body = $arr_buf[1];

$header = preg_replace('/^X-Request.+\n/m', '', $header);
$header = preg_replace('/^ETag.+\n/m', '', $header);
$header = preg_replace('/^Expires.+\n/m', '', $header);
// 偽装
$header = preg_replace('/^Server: DeleGate.+$/m', 'Server: Apache', $header);
$header = preg_replace('/^DeleGate.+\n/m', '', $header);

if (strpos($header, 'Content-Type: text/html') !== false)
{
  $header = preg_replace('/^Last-Modified.+\n/m', '', $header);
  
  // 元サイズ
  $header = str_replace('Content-Length:', 'X-Content-Length:', $header);
  
  $tmp = explode('/', $_SERVER['REQUEST_URI']);
  
  if (preg_match('/^\d+$/', end($tmp)))
  {
    $body = str_replace('<TITLE>', '<HTML><HEAD><TITLE>', $body);
  }
  else
  {
    // 自動更新追加
    $body = str_replace('<TITLE>', '<HTML><HEAD><META HTTP-EQUIV="REFRESH" CONTENT="600"><TITLE>', $body);
  }
  $body = str_replace('</TITLE>', '</TITLE></HEAD>', $body);

  // アイコンはフロント側から取得
  $body = str_replace('http://' . $_SERVER['SERVER_NAME'] . ':80/-/builtin/icons/ysato/', '/icons/', $body);
  //$body = str_replace('/-/builtin/icons/ysato/', '/icons/', $body);

  $body = preg_replace('/<FORM ACTION="..\/-search" METHOD=GET>.+?<\/FORM>/s', '', $body);
  //$body = preg_replace('/<FORM ACTION="\/mail\/-search" METHOD=GET>.+?<\/FORM>/s', '', $body);

  $body = preg_replace('/<!-- generated by DeleGate\/x.x.x -->.+/s', '</BODY></HTML>', $body);

  $body = str_replace('<A HREF="../"><IMG BORDER=0 ALIGN=MIDDLE ALT="upper" SRC="/icons/up.gif"></A>', '', $body);
  //$body = str_replace('<A HREF="/mail/"><IMG BORDER=0 ALIGN=MIDDLE ALT="upper" SRC="/icons/up.gif"></A>', '', $body);

  $body = preg_replace('/<FONT .+?>.+?<\/FONT>/s', '', $body, 1);

  $body = preg_replace('/<small>.+?<\/small>/s', '', $body, 3);
  
  // 空白削除
  $body = preg_replace('/^ *\r\n/m', '', $body);
  $body = preg_replace('/^  /m', ' ', $body);
  $body = preg_replace('/^ +</m', '<', $body);

  error_log($_SERVER['REQUEST_URI']);
  error_log($header);
  error_log("\r\n");
  error_log($body);

  $buf = $header;
  $body = gzencode($body, 9);

  $buf .= "Content-Encoding: gzip\r\n";
  $buf .= "Content-Length: " . strlen($body) . "\r\n";
  $buf .= "\r\n";
  $buf .= $body;
} else {
  error_log($_SERVER['REQUEST_URI']);
  error_log($header);
  $buf = $header;
  //$buf .= "Cache-Control: max-age=86400\r\n";
  $buf .= "\r\n";
  $buf .= $body;
}

echo $buf;

$http_status_code = explode(' ', $header, 3)[1];

$message =
  'D ' .
  $http_status_code . ' ' .
  $_SERVER['SERVER_NAME'] . ' ' .
  $_SERVER['HTTP_X_FORWARDED_FOR'] . ' ' .
  $_SERVER['REMOTE_USER'] . ' ' .
  $_SERVER['REQUEST_METHOD'] . ' ' .
  $_SERVER['REQUEST_URI'] . ' ' .
  $_SERVER['HTTP_USER_AGENT'];

$context = array(
  "http" => array(
    "method" => "POST",
    "header" => array(
      "Content-Type: text/plain"
      ),
    "content" => $message
    )
  );

$res = file_get_contents($url, false, stream_context_create($context));

error_log($pid . ' ' . $res);

error_log($pid . ' ***** FILTER MESSAGE FINISH ***** ' . $_SERVER['REQUEST_URI']);
?>
